spring:
    batch:
        job:
            names: ${job.name:NONE}
    jpa:
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDB103Dialect
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/srs
        username: srs
        password: srs123!!
logging:
    level:
        root: info
        com.jaewoo.srs.batch: debug
